name: Maven CI/CD
on:
  push:
    branches:
      - main
jobs:
#  build_and_test:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#      - name: Setup JDK 17
#        uses: actions/setup-java@v1
#        with:
#          java-version: 17
#      - name: Build project with Maven
#        run: mvn -B package --file pom.xml
  build_and_push:
#    name: Publish to Docker Hub
    runs-on: ubuntu-latest
#    needs: [build_and_test]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
#      - name: Login to docker hub
#        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
#      - name: Build container image
#        run: docker build -t ghcr.io/${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:1.0.0 .
#      - name: Publish docker image
#        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:latest
      - name: Login to GitHub Container Registery
#        if: success()
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image from repository
#        run: docker build -t ghcr.io/${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:1.0.0 .
        run: docker build -t ghcr.io/${{ github.actor }}/github-action:latest .
      - name: Publish to Github Container registry
        run: docker push ghcr.io/${{ github.actor}}/github-action:latest

